# Generated by Django 4.1.7 on 2023-03-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('library_name', models.CharField(max_length=200)),
                ('max_checkout_days', models.SmallIntegerField()),
                ('late_fees', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
    ]
