# Generated by Django 4.1.7 on 2023-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksReservations',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.PositiveIntegerField(auto_created=True, blank=True, primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'books_reservations',
                'managed': False,
            },
        ),
    ]
